### ISSUE TITLE
Client throws Connection is still allocated if 500 is returned and does not recover

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-rest-client#19]
Version 1.0
Reproducer: https://gitlab.com/pilhuhn/ece2018-mp/tree/0b987ea152db757aca961811308131187cadb218 run `./start.sh` in frontenad service and backend. Invoke `curl localhost:8080?mode=fail && curl localhost:8080?mode=ok`. Then all following calls go to fallback and the following exception is logged.

See https://gitlab.com/pilhuhn/ece2018-mp/issues/2

```bash
018-10-16 16:35:09,397 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) java.lang.reflect.UndeclaredThrowableException
2018-10-16 16:35:09,397 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.sun.proxy.$Proxy110.getRandom(Unknown Source)
2018-10-16 16:35:09,397 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at de.bsd.ece2018.frontend.BackendService.getGreeting(BackendService.java:77)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at de.bsd.ece2018.frontend.BackendService$Proxy$_$$_WeldSubclass.getGreeting$$super(Unknown Source)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at io.smallrye.faulttolerance.ExecutionContextWithInvocationContext.proceed(ExecutionContextWithInvocationContext.java:50)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at io.smallrye.faulttolerance.SimpleCommand.run(SimpleCommand.java:73)
2018-10-16 16:35:09,398 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2018-10-16 16:35:09,399 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.Observable.unsafeSubscribe(Observable.java:10256)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.Observable.unsafeSubscribe(Observable.java:10256)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.Observable.unsafeSubscribe(Observable.java:10256)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
2018-10-16 16:35:09,400 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.lang.Thread.run(Thread.java:748)
2018-10-16 16:35:09,401 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) Caused by: java.lang.reflect.InvocationTargetException
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-10-16 16:35:09,402 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at io.smallrye.restclient.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:148)
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	... 41 more
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:317)
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102)
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
2018-10-16 16:35:09,403 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at com.sun.proxy.$Proxy109.getRandom(Unknown Source)
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	... 46 more
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) Caused by: java.lang.IllegalStateException: Connection is still allocated
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.util.Asserts.check(Asserts.java:34)
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.getConnection(BasicHttpClientConnectionManager.java:266)
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.conn.BasicHttpClientConnectionManager$1.get(BasicHttpClientConnectionManager.java:217)
2018-10-16 16:35:09,404 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:313)
2018-10-16 16:35:09,405 ERROR [stderr] (EE-ManagedThreadFactory-default-Thread-10) 	... 50 more

```

**Comment by michalszynkiewicz** [comment]
should be fixed with https://github.com/smallrye/smallrye-rest-client/pull/12/files

**Comment by pavolloffay** [comment]
Feel free to close then.
