### ISSUE TITLE
NPE in getBeanManager in ProxyInvocationHandler

### ISSUE THREAD

**Issue by doychin** [smallrye/smallrye-rest-client#57]
If a CDI provider is available but not CDI container is created getBeanManager produces NPE.

java.lang.NullPointerException
	at io.smallrye.restclient.ProxyInvocationHandler.getBeanManager(ProxyInvocationHandler.java:228)
	at io.smallrye.restclient.ProxyInvocationHandler.<init>(ProxyInvocationHandler.java:81)
	at io.smallrye.restclient.RestClientBuilderImpl.build(RestClientBuilderImpl.java:175)

**Comment by kenfinnigan** [comment]
Can you provide some details of the environment this is running in?
