### ISSUE TITLE
RestClientBuilderImpl does not handle @BeanParam 

### ISSUE THREAD

**Issue by chonton** [smallrye/smallrye-rest-client#69]
I have the following Api interface
```java
package com.example.api;

import javax.ws.rs.BeanParam;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.core.MediaType;

@Path("/v1/example")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface ExampleApi {
  @Path("/{cluster}/{service}/{name:.+}")
  @POST
  String createBlob(@BeanParam Location location);
}
```
The Location class is
```java
package com.example.api;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.ws.rs.PathParam;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Location {
  public static final String SEGMENT_REGEX = "[\\w-]{1,64}";

  @PathParam("cluster")
  @NotNull
  @Pattern(regexp = SEGMENT_REGEX)
  private String cluster;

  @PathParam("service")
  @NotNull
  @Pattern(regexp = SEGMENT_REGEX)
  private String service;

  @PathParam("name")
  @NotNull
  @Pattern(regexp = SEGMENT_REGEX + "(/" + SEGMENT_REGEX + ")*")
  private String name;
}
```

The following code fails
```java
RestClientBuilder.newBuilder().baseUri(getConnection()).build(ExampleApi.class);
``` 
with the exception
```
org.eclipse.microprofile.rest.client.RestClientDefinitionException: Parameters and variables don't match on interface com.example.api.ExampleApi::createBlob
	at io.smallrye.restclient.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:285)
	at io.smallrye.restclient.RestClientBuilderImpl.build(RestClientBuilderImpl.java:138)
	at com.example.api.MainTest.createClient(MainTest.java:64)
```

If I use Resteasy client directly, there is no exception.  Why does ```RestClientBuilderImpl``` have the checks in the ```verifyInterface``` method?  I believe that RestEasy client already has extensive validation.

**Comment by kenfinnigan** [comment]
Closing as implementation has been moved to https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile
